INFO 09-01 02:32:44 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
Initializing LLM with model: Qwen/Qwen2.5-7B-Instruct
INFO 09-01 02:33:39 [utils.py:326] non-default args: {'model': 'Qwen/Qwen2.5-7B-Instruct', 'trust_remote_code': True, 'dtype': 'float16', 'distributed_executor_backend': 'mp', 'gpu_memory_utilization': 0.92, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 02:33:46 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
WARNING 09-01 02:33:46 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 02:33:46 [__init__.py:1750] Using max model len 32768
INFO 09-01 02:33:47 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 02:33:47 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 02:33:48 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 02:33:53 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=1152953)[0;0m INFO 09-01 02:33:55 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1152953)[0;0m INFO 09-01 02:33:55 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1152953)[0;0m WARNING 09-01 02:33:55 [multiproc_worker_utils.py:273] Reducing Torch parallelism from 48 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_0 pid=1152953)[0;0m INFO 09-01 02:33:55 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 16777216, 10, 'psm_cfe8b6a2'), local_subscribe_addr='ipc:///data/cl195/tmp/3fbdda0f-b3b8-4f00-b384-fbd08d61e5f6', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 09-01 02:34:00 [__init__.py:241] Automatically detected platform cuda.
[1;36m(VllmWorker pid=1153106)[0;0m INFO 09-01 02:34:04 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_17038a98'), local_subscribe_addr='ipc:///data/cl195/tmp/d75d7c8a-44c8-436c-aa3f-ffb09c6e9aed', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559] WorkerProc failed to start.
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559] Traceback (most recent call last):
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 533, in worker_main
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]     worker = WorkerProc(*args, **kwargs)
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 401, in __init__
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]     self.worker.init_device()
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]     self.worker.init_device()  # type: ignore
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559]     raise ValueError(
[1;36m(VllmWorker pid=1153106)[0;0m ERROR 09-01 02:34:04 [multiproc_executor.py:559] ValueError: Free memory on device (31.63/47.53 GiB) on startup is less than desired GPU memory utilization (0.92, 43.73 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
[1;36m(VllmWorker pid=1153106)[0;0m INFO 09-01 02:34:04 [multiproc_executor.py:520] Parent process exited, terminating worker
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 96, in _init_executor
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]     self.workers = WorkerProc.wait_for_ready(unready_workers)
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 472, in wait_for_ready
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700]     raise e from None
[1;36m(EngineCore_0 pid=1152953)[0;0m ERROR 09-01 02:34:06 [core.py:700] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
INFO 09-01 02:39:21 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
Initializing LLM with model: Qwen/Qwen2.5-7B-Instruct
INFO 09-01 02:40:17 [utils.py:326] non-default args: {'model': 'Qwen/Qwen2.5-7B-Instruct', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.92, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 02:40:24 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
WARNING 09-01 02:40:24 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 02:40:24 [__init__.py:1750] Using max model len 32768
INFO 09-01 02:40:25 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 02:40:25 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 02:40:26 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 02:40:31 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=1155685)[0;0m INFO 09-01 02:40:33 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1155685)[0;0m INFO 09-01 02:40:34 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700]     raise ValueError(
[1;36m(EngineCore_0 pid=1155685)[0;0m ERROR 09-01 02:40:35 [core.py:700] ValueError: Free memory on device (32.35/47.53 GiB) on startup is less than desired GPU memory utilization (0.92, 43.73 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
INFO 09-01 02:41:55 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
Initializing LLM with model: Qwen/Qwen2.5-7B-Instruct
INFO 09-01 02:42:51 [utils.py:326] non-default args: {'model': 'Qwen/Qwen2.5-7B-Instruct', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.99, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 02:42:58 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
WARNING 09-01 02:42:58 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 02:42:58 [__init__.py:1750] Using max model len 32768
INFO 09-01 02:42:58 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 02:42:58 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 02:42:59 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 02:43:05 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=1156949)[0;0m INFO 09-01 02:43:07 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1156949)[0;0m INFO 09-01 02:43:07 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700]     raise ValueError(
[1;36m(EngineCore_0 pid=1156949)[0;0m ERROR 09-01 02:43:09 [core.py:700] ValueError: Free memory on device (32.35/47.53 GiB) on startup is less than desired GPU memory utilization (0.99, 47.05 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
INFO 09-01 06:09:23 [__init__.py:241] Automatically detected platform cuda.
Initializing LLM with model: Qwen/Qwen3-4B
INFO 09-01 06:09:24 [utils.py:326] non-default args: {'model': 'Qwen/Qwen3-4B', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 1.0, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 06:09:31 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
WARNING 09-01 06:09:31 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 06:09:31 [__init__.py:1750] Using max model len 40960
INFO 09-01 06:09:31 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 06:09:31 [__init__.py:3565] Cudagraph is disabled under eager mode
[1;36m(EngineCore_0 pid=1353171)[0;0m INFO 09-01 06:09:33 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1353171)[0;0m INFO 09-01 06:09:33 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen3-4B', speculative_config=None, tokenizer='Qwen/Qwen3-4B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=40960, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen3-4B, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700]     raise ValueError(
[1;36m(EngineCore_0 pid=1353171)[0;0m ERROR 09-01 06:09:35 [core.py:700] ValueError: Free memory on device (44.55/47.53 GiB) on startup is less than desired GPU memory utilization (1.0, 47.53 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
INFO 09-01 06:10:51 [__init__.py:241] Automatically detected platform cuda.
Initializing LLM with model: Qwen/Qwen3-8B
INFO 09-01 06:10:52 [utils.py:326] non-default args: {'model': 'Qwen/Qwen3-8B', 'trust_remote_code': True, 'dtype': 'float16', 'tensor_parallel_size': 0.8, 'gpu_memory_utilization': 1.0, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 06:10:59 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
WARNING 09-01 06:10:59 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 06:10:59 [__init__.py:1750] Using max model len 40960
INFO 09-01 06:18:23 [__init__.py:241] Automatically detected platform cuda.
Initializing LLM with model: Qwen/Qwen3-8B
INFO 09-01 06:18:24 [utils.py:326] non-default args: {'model': 'Qwen/Qwen3-8B', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 1.0, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 06:18:31 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
WARNING 09-01 06:18:31 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 06:18:31 [__init__.py:1750] Using max model len 40960
INFO 09-01 06:18:31 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 06:18:31 [__init__.py:3565] Cudagraph is disabled under eager mode
[1;36m(EngineCore_0 pid=1355465)[0;0m INFO 09-01 06:18:32 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1355465)[0;0m INFO 09-01 06:18:32 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen3-8B', speculative_config=None, tokenizer='Qwen/Qwen3-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=40960, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen3-8B, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700]     raise ValueError(
[1;36m(EngineCore_0 pid=1355465)[0;0m ERROR 09-01 06:18:34 [core.py:700] ValueError: Free memory on device (44.55/47.53 GiB) on startup is less than desired GPU memory utilization (1.0, 47.53 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
INFO 09-01 06:19:14 [__init__.py:241] Automatically detected platform cuda.
Initializing LLM with model: Qwen/Qwen3-8B
INFO 09-01 06:19:14 [utils.py:326] non-default args: {'model': 'Qwen/Qwen3-8B', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.8, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 06:19:27 [__init__.py:241] Automatically detected platform cuda.
Initializing LLM with model: Qwen/Qwen3-8B
INFO 09-01 06:19:28 [utils.py:326] non-default args: {'model': 'Qwen/Qwen3-8B', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.8, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 06:19:34 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
WARNING 09-01 06:19:34 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 06:19:34 [__init__.py:1750] Using max model len 40960
INFO 09-01 06:19:35 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 06:19:35 [__init__.py:3565] Cudagraph is disabled under eager mode
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:36 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:36 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen3-8B', speculative_config=None, tokenizer='Qwen/Qwen3-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=40960, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen3-8B, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:38 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
[1;36m(EngineCore_0 pid=1356323)[0;0m WARNING 09-01 06:19:38 [topk_topp_sampler.py:61] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:38 [gpu_model_runner.py:1953] Starting to load model Qwen/Qwen3-8B...
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:39 [gpu_model_runner.py:1985] Loading model from scratch...
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:39 [cuda.py:328] Using Flash Attention backend on V1 engine.
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:39 [weight_utils.py:296] Using model weights format ['*.safetensors']
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:43 [default_loader.py:262] Loading weights took 4.28 seconds
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:44 [gpu_model_runner.py:2007] Model loading took 15.2683 GiB and 4.733610 seconds
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:46 [gpu_worker.py:276] Available KV cache memory: 21.29 GiB
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:46 [kv_cache_utils.py:849] GPU KV cache size: 155,008 tokens
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:46 [kv_cache_utils.py:853] Maximum concurrency for 40,960 tokens per request: 3.78x
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:46 [core.py:214] init engine (profile, create kv cache, warmup model) took 2.20 seconds
[1;36m(EngineCore_0 pid=1356323)[0;0m INFO 09-01 06:19:46 [__init__.py:3565] Cudagraph is disabled under eager mode
INFO 09-01 06:19:47 [llm.py:298] Supported_tasks: ['generate']
[1;36m(EngineCore_0 pid=1356323)[0;0m WARNING 09-01 06:19:47 [cudagraph_dispatcher.py:101] cudagraph dispatching keys are not initialized. No cudagraph will be used.
ERROR 09-01 06:20:25 [core_client.py:562] Engine core proc EngineCore_0 died unexpectedly, shutting down client.
INFO 09-01 06:24:27 [__init__.py:241] Automatically detected platform cuda.
Initializing LLM with model: Qwen/Qwen3-8B
INFO 09-01 06:24:29 [utils.py:326] non-default args: {'model': 'Qwen/Qwen3-8B', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.8, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 06:24:35 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
WARNING 09-01 06:24:35 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 06:24:35 [__init__.py:1750] Using max model len 40960
INFO 09-01 06:24:36 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 06:24:36 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 06:24:37 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 06:24:41 [__init__.py:241] Automatically detected platform cuda.
Initializing LLM with model: Qwen/Qwen3-8B
INFO 09-01 06:24:44 [utils.py:326] non-default args: {'model': 'Qwen/Qwen3-8B', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.8, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 06:24:52 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
WARNING 09-01 06:24:52 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 06:24:52 [__init__.py:1750] Using max model len 40960
INFO 09-01 06:24:53 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 06:24:53 [__init__.py:3565] Cudagraph is disabled under eager mode
INFO 09-01 06:26:48 [__init__.py:241] Automatically detected platform cuda.
Initializing LLM with model: Qwen/Qwen3-8B
INFO 09-01 06:26:50 [utils.py:326] non-default args: {'model': 'Qwen/Qwen3-8B', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.8, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 06:26:59 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
WARNING 09-01 06:26:59 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 06:26:59 [__init__.py:1750] Using max model len 40960
INFO 09-01 06:27:00 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 06:27:00 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 06:27:01 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 06:27:07 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:10 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:10 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen3-8B', speculative_config=None, tokenizer='Qwen/Qwen3-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=40960, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen3-8B, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:12 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
[1;36m(EngineCore_0 pid=1359894)[0;0m WARNING 09-01 06:27:12 [topk_topp_sampler.py:61] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:12 [gpu_model_runner.py:1953] Starting to load model Qwen/Qwen3-8B...
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:12 [gpu_model_runner.py:1985] Loading model from scratch...
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:13 [cuda.py:328] Using Flash Attention backend on V1 engine.
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:13 [weight_utils.py:296] Using model weights format ['*.safetensors']
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:17 [default_loader.py:262] Loading weights took 4.29 seconds
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:18 [gpu_model_runner.py:2007] Model loading took 15.2683 GiB and 4.662740 seconds
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:20 [gpu_worker.py:276] Available KV cache memory: 21.29 GiB
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:20 [kv_cache_utils.py:849] GPU KV cache size: 155,008 tokens
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:20 [kv_cache_utils.py:853] Maximum concurrency for 40,960 tokens per request: 3.78x
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:20 [core.py:214] init engine (profile, create kv cache, warmup model) took 2.26 seconds
[1;36m(EngineCore_0 pid=1359894)[0;0m INFO 09-01 06:27:20 [__init__.py:3565] Cudagraph is disabled under eager mode
INFO 09-01 06:27:21 [llm.py:298] Supported_tasks: ['generate']
[1;36m(EngineCore_0 pid=1359894)[0;0m WARNING 09-01 06:27:21 [cudagraph_dispatcher.py:101] cudagraph dispatching keys are not initialized. No cudagraph will be used.
ERROR 09-01 06:28:05 [core_client.py:562] Engine core proc EngineCore_0 died unexpectedly, shutting down client.
INFO 09-01 06:28:38 [__init__.py:241] Automatically detected platform cuda.
Initializing LLM with model: Qwen/Qwen3-8B
INFO 09-01 06:28:40 [utils.py:326] non-default args: {'model': 'Qwen/Qwen3-8B', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.8, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 06:28:47 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
WARNING 09-01 06:28:47 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 06:28:47 [__init__.py:1750] Using max model len 40960
INFO 09-01 06:28:47 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 06:28:47 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 06:28:48 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 06:28:53 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:28:55 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:28:55 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen3-8B', speculative_config=None, tokenizer='Qwen/Qwen3-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=40960, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen3-8B, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:28:57 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
[1;36m(EngineCore_0 pid=1361200)[0;0m WARNING 09-01 06:28:57 [topk_topp_sampler.py:61] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:28:57 [gpu_model_runner.py:1953] Starting to load model Qwen/Qwen3-8B...
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:28:58 [gpu_model_runner.py:1985] Loading model from scratch...
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:28:58 [cuda.py:328] Using Flash Attention backend on V1 engine.
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:28:58 [weight_utils.py:296] Using model weights format ['*.safetensors']
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:29:02 [default_loader.py:262] Loading weights took 4.36 seconds
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:29:03 [gpu_model_runner.py:2007] Model loading took 15.2683 GiB and 4.797947 seconds
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:29:05 [gpu_worker.py:276] Available KV cache memory: 21.29 GiB
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:29:05 [kv_cache_utils.py:849] GPU KV cache size: 155,008 tokens
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:29:05 [kv_cache_utils.py:853] Maximum concurrency for 40,960 tokens per request: 3.78x
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:29:05 [core.py:214] init engine (profile, create kv cache, warmup model) took 2.23 seconds
[1;36m(EngineCore_0 pid=1361200)[0;0m INFO 09-01 06:29:06 [__init__.py:3565] Cudagraph is disabled under eager mode
INFO 09-01 06:29:06 [llm.py:298] Supported_tasks: ['generate']
[1;36m(EngineCore_0 pid=1361200)[0;0m WARNING 09-01 06:29:06 [cudagraph_dispatcher.py:101] cudagraph dispatching keys are not initialized. No cudagraph will be used.
Saved results to ./csv_paragraph_generation2_result.csv
ERROR 09-01 06:29:49 [core_client.py:562] Engine core proc EngineCore_0 died unexpectedly, shutting down client.
